name: Notify Admin via Email

on:
  push:
    branches:
      - main

jobs:
  notify-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email on Push
        run: |
          echo "Sending email..."
          curl -X POST https://api.sendgrid.com/v3/mail/send \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "personalizations": [{
                "to": [{"email": "'"${{ secrets.TO_EMAIL }}"'"}],
                "subject": "GitHub Push Notification"
              }],
              "from": {"email": "'"${{ secrets.FROM_EMAIL }}"'"},
              "content": [{
                "type": "text/plain",
                "value": "Code was pushed to the main branch on GitHub by '${{ github.actor }}'"
              }]
            }'
